version: 2.1

jobs:
  install-deps:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: yarn
      - save_cache:
          paths:
            - node_modules
            - website/node_modules
          key: dependencies
  lsif-node:
    docker:
      - image: sourcegraph/lsif-node@sha256:943e620468baa9c1ad01a469e4ada02221105c6c4172542c8136965e482db791
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies
      - run: lsif-tsc -p .
      - run: src lsif upload -no-progress

workflows:
  lsif-node:
    jobs:
      - install-deps
      - lsif-node:
          requires:
            - install-deps
